apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: podlister
  name: podlister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podlister
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: podlister
    spec:
      containers:
      - image: bisakh/k8s.example:0.2
        name: k8s-example-t7ssb
        resources: {}
status: {}
